imports:
- https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  webapp:
    sources:
      app:
        repository: https://github.com/fkpama/Crank-WebApp.git
    project: app/Crank-BenchmarkApp/Crank-BenchmarkApp.csproj
    readyStateText: Application started.
    environmentVariables:
      ASPNETCORE_ENVIRONMENT: Development

  benchmark_dotnet:
    sources:
      app:
        repository: https://github.com/fkpama/Crank-WebApp.git
    project: app/Crank-BenchmarkDotnet/Crank-BenchmarkDotnet.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    options:
      benchmarkDotNet: true

scenarios:
  webapp:
    server:
      job: webapp

    client_app:
      job: bombardier

  benchmarks:
    server:
      job: benchmark_dotnet


profiles:
  build-agent:
    jobs:
      server:
        endpoints:
          - http://crank-agent:5010

      client_app:
        endpoints:
          - http://crank-agent-2:5010

  local:
    jobs:
      server:
        endpoints:
          - http://localhost:5010

      client_app:
        endpoints:
          - http://localhost:5011
